/** Rebuild from final executed notebook evidence. Requires bundled @oai/artifact-tool. */
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'..');
const runtime=process.env.ARTIFACT_NODE_MODULES || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const skill=process.env.PRESENTATIONS_SKILL_DIR || path.join(os.homedir(),'.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations');
process.env.RUNTIME_NODE_MODULES=runtime;
const {Presentation,PresentationFile,FileBlob}=await import(pathToFileURL(path.join(runtime,'@oai/artifact-tool/dist/artifact_tool.mjs')));
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')));
const evidence=JSON.parse(await fs.readFile(path.join(root,'docs/deck-evidence.json'),'utf8'));
const out=path.join(root,'.build/deck'); await fs.mkdir(out,{recursive:true});
const font=resolvePresentationFont();
const p=Presentation.create({slideSize:{width:1280,height:720}});
const ink='#152C3A', teal='#007C83', gray='#526874', paper='#F7F8F5';
const all=[];
function text(s,t,x,y,w,h,size=28,color=ink,bold=false){const z=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});z.text=t;z.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return z;}
function slide(title,notes,{dark=false}={}){const s=p.slides.add();s.background.fill=dark?ink:paper;text(s,title,70,50,1140,100,42,dark?'#FFFFFF':ink,true);text(s,String(p.slides.items.length).padStart(2,'0'),1180,665,45,30,18,dark?'#C7DBDE':gray);s.speakerNotes.textFrame.setText(notes+'\nSource: notebooks/SPC_ML_Demo.py and final executed synthetic-run evidence. Counts and outcomes are synthetic.');all.push({title,notes});return s;}
function body(s,lines,y=180,size=29){lines.forEach((v,i)=>text(s,v,75,y+i*100,1100,85,size));}
function table(s,values,top=190,widths){const t=s.tables.add({rows:values.length,columns:values[0].length,left:75,top,width:1130,height:values.length*(values.length>6?50:58),values,columnWidths:widths});for(let r=0;r<values.length;r++)for(let c=0;c<values[0].length;c++){let z=t.getCell(r,c);z.fill=r===0?ink:(r%2?'#FFFFFF':'#EAF0F0');z.text.style={typeface:font,fontSize:23,color:r===0?'#FFFFFF':ink,bold:r===0};}return t;}
function chart(s,type,categories,series,pos){const c=s.charts.add(type,{position:pos,categories,series,hasLegend:series.length>1,legend:{position:'bottom',overlay:false,textStyle:{fontSize:20}},yAxis:{title:'Daily application count',numberFormatCode:'0',textStyle:{fontSize:18}},xAxis:{title:'Business days (latest observations)',textStyle:{fontSize:16}},barOptions:{direction:'column',grouping:'clustered'},dataLabels:{showValue:type==='bar',position:'outEnd'}});applyPresentationChartFont(c,{fontFamily:font});return c;}
let s=slide('Daily application volumes\nSPC and machine learning', 'Opening: This is a synthetic USCIS-related workload demonstration. Daily receipts and completions represent aggregate operational counts. We look for unusual patterns, route them to an analyst, and separately estimate future volume. No applicant decisions or agency performance claims follow from this demonstration.',{dark:true});
text(s,'An unusual pattern starts an analyst review',75,315,1100,65,34,'#8EDCDA');text(s,'Synthetic receipts and completions\nA reproducible Databricks demonstration',75,490,1060,95,27,'#FFFFFF');
s=slide('The operational question','Explain the workflow without model terminology first. A workload owner wants to know which recent volume changes deserve attention. A reviewer checks source completeness, calendar effects, workload changes and operational context. The disposition belongs to a human. Future workload planning is a different question.');body(s,['Daily counts arrive for receipts and completions.','A change may reflect workload, an operating change or a data issue.','An analyst checks the evidence and records a disposition.','Future-volume estimates support a separate planning discussion.']);
s=slide('Synthetic daily counts',`Dataset: ${evidence.dataset}. ${evidence.dataSummary} Over a million event rows do not mean over a million independent training examples. The models train on daily-series feature windows. Calendar and generation settings come from the executed notebook. The chart labels Receipts A and Receipts B map to notebook series_id Intake A and Intake B. Completions A retains the same name. There are no applicant records. Do not describe these counts as historical USCIS outcomes.`);
chart(s,'line',evidence.volume.categories,evidence.volume.series,{left:75,top:175,width:1120,height:385});text(s,evidence.dataSummary,75,590,1110,66,24,gray);
s=slide('Statistical process control (SPC)','SPC compares recent observations with a historical reference. XmR checks large deviations. CUSUM accumulates small departures. EWMA smooths observations to expose shifts. Their OR forms the classifier label. Separate severity zones add point and run rules. Control limits characterize reference variation. They do not establish mission targets or explain causes. Show the notebook rule flags, contributing daily rows and one review episode.');body(s,['1   Measure recent counts against a historical reference.','2   Apply explicit SPC rules and retain the contributing rows.','3   Group repeated signals into an episode for review.','4   Check source quality and context before deciding what to do.']);
s=slide('Each method answers a different question','Keep the distinction explicit. SPC is direct deterministic logic. The classifier learns a proxy label generated by that logic. Isolation Forest learns unusual feature patterns without incident labels. Regression and statistical time-series methods estimate future counts. None determines a root cause or authorizes action. SPC label construction finishes in notebook Cell 4 and machine learning first appears in Cell 5; each notebook cell names its method type.');table(s,[['Method','Question'],['Statistics: SPC rules','Did a defined control rule fire?'],['ML: random forest / logistic classifier','Can learned features reproduce the rule label?'],['ML: Isolation Forest','Does this pattern differ from training history?'],['ML: random forest regression','What count may occur next business day?'],['Statistics: ARIMA / Holt-Winters','What counts may occur over the next five days?']],175,[430,700]);
s=slide('Training uses earlier dates','Walk through the measurement features before describing algorithms. During fit, the random forest grows decision trees on sampled training rows and feature subsets. Each tree learns split thresholds that separate the rule labels. Voting across trees gives a class and a vote-based score. The regressor averages tree predictions for counts. A saved model retains those learned splits for inference. Each classification row summarizes a prior window. The label is the OR of explicit rule flags. Chronological splitting prevents later dates from training earlier predictions. A 25-business-day separation prevents overlap of 25-day measurement windows. Earlier 90-day references can overlap. This is not independent incident validation.');body(s,[evidence.trainingSummary,'Inputs describe level, spread, recent movement and reference deviation.','Target: whether the direct SPC rules flagged that window.','Later unseen dates test reproduction of those rules.']);
s=slide('The comparison determines the conclusion','These are executed synthetic-run results. The classification target is the rule label, not a confirmed incident. Each experiment reports its always-signal constant beside the models, on the same metric. The rolling-fold comparison is a separate experiment from the single holdout. Do not assume that a more complex algorithm wins.');table(s,evidence.classificationTable,185,evidence.classificationWidths);text(s,evidence.classificationConclusion,75,550,1110,85,28,teal,true);
s=slide('Forecasting has a separate target','The regressor predicts the next business-day count using history available at forecast time. The five-day comparison evaluates statistical models over multiple origins. Lower mean absolute error is better. Horizons and samples differ, so do not rank one-day and five-day methods against each other. Candidate selection uses earlier origins, with a final origin held aside.');table(s,evidence.forecastTable,175,[490,310,330]);text(s,evidence.forecastConclusion,75,570,1100,80,26,teal,true);
s=slide('An analyst owns the disposition','Show one episode and its lineage, source freshness and possible operational events. An automatically proposed hypothesis is a prompt to investigate. The notebook replay contains simulated dispositions and a prepared outbox. It does not send messages or establish real human review. A production reviewer can acknowledge, investigate, request data correction or close with evidence.');body(s,['Review the signal and contributing counts.','Check completeness, timing and upstream dependencies.','Record a supported explanation or leave the cause unresolved.','Assign follow-up, then retain the decision and evidence.']);
s=slide('A saved model is reused without retraining','Explain training versus inference. Training learns parameters from the permitted earlier history. A persisted artifact stores the model. Loading it later and calling predict reuses those parameters without fitting again. The scorer replays saved, already engineered inputs; a feature pipeline for new days is separate work. Demonstrated local persistence and target-platform MLflow logging are separate proof levels.');body(s,[evidence.reuseSummary,'The feature contract and model version travel with the artifact.','A later scoring run loads the model and predicts without refitting.','Production promotion requires validation, approval and rollback.']);
s=slide('Monitoring supports retraining review','Input drift means feature distributions changed. Performance drift means error changes after actual outcomes arrive. Either can motivate investigation. Neither proves the cause. Demonstration thresholds are illustrative: input change above 0.5 training standard deviations prompts investigation, and two consecutive 25-day windows above 1.25 times the reference MAE, each with at least 20 actuals, request review. A controlled exercise perturbs outcomes while retaining predictions to show watch and review states. No automatic retraining or deployment occurs.');body(s,['Monitor inputs and data quality before outcomes arrive.','Match predictions to mature actuals and compare baseline error.',evidence.driftSummary,'Investigate first. Compare a candidate on later dates before promotion.']);
s=slide('What this demonstration establishes','Close by separating runnable demonstration capability from production acceptance. We can demonstrate the pipeline and decision records on synthetic data. A pilot needs approved representative data, a workload owner, outcome definitions and operating thresholds. Run it prospectively in shadow mode before promoting a model. No labor savings, real-world accuracy or historical agency outcomes are established.');body(s,['A reproducible path from daily counts to evidence for review.','Measured model comparisons and a saved-model scoring example.','A pilot still needs representative data and agreed success criteria.','Human approval controls operational decisions and model promotion.']);
s=slide('Appendix A   Data and feature contract','Technical reference. The daily table contains aggregate synthetic workload counts. Subgroup rows must reconcile to their parent. A rolling measurement row is not a daily-count row. Preserve time semantics across daily counts, features, episodes and forecasts.');body(s,[evidence.dataSummary,'12 classifier features: window level and spread, moving range, latest value, recent mean and spread, trend, reference level and spread, two deviations.','25-day measurement windows and 90-day reference histories.','Destination schema: ml_statistical_process_controls.demo_schema'],170,26);
s=slide('Appendix B   Model training details','All settings here match the notebook. The holdout and rolling-fold random forests share one configuration; the folds are a separate later-period experiment. Logistic regression standardizes inputs. Isolation Forest does not train on incident labels and its training-derived contamination heuristic does not reveal a true incident rate. ARIMA and Holt-Winters refit at each forecast origin.');table(s,[['Model','Training configuration'],['RF classifier (holdout and folds)',evidence.classifierConfig],['Logistic regression','StandardScaler, max_iter 1000'],['Isolation Forest',`100 trees, train-derived contamination ${evidence.isolationContamination.toFixed(4)}`],['Next-day RF regressor','120 trees, depth 7, leaf minimum 4'],['ARIMA / Holt-Winters','AR(1) with constant; damped trend, 5-day seasonality; last 180 days']],175,[390,740]);
s=slide('Appendix C   Validation and uncertainty','Describe limitations before generalizing results. Synthetic labels and generation patterns are simplified. Chronological tests support ordering but do not establish broad external validity. Class imbalance makes accuracy insufficient. The illustrative limits flag most windows; calibrating them against confirmed outcomes is pilot work. Prediction intervals and calibration require separate assessment where absent. Five-day subgroup forecasts are independent and need not reconcile to the aggregate.');body(s,['Classification measures rule reproduction on synthetic data.','Report class balance, confusion counts and fold variability.',evidence.validationSummary,'Forecast horizon, calendar and evaluation origins define each score.'],170,27);
s=slide('Appendix D   Deployment and monitoring','This slide describes the intended production lifecycle, not verified live deployment. Daily jobs score new data with a versioned approved model, write appendable predictions, and wait for actual outcomes. Dashboards read persisted tables. An owner reviews alert burden and model performance. Data correction precedes retraining when appropriate.');body(s,['1   Validate approved data and stable feature definitions.','2   Version the candidate, compare later dates and approve promotion.','3   Schedule scoring, retain predictions and match actual outcomes.','4   Review drift, retrain when justified and retain rollback.']);
s=slide('Appendix E   Scope and boundaries','Use these answers consistently. This is an aggregate workload demonstration, not case adjudication. It detects statistical patterns without proving operational cause. Synthetic experiments cannot demonstrate agency accuracy or labor savings. Local checks do not prove a scheduled Databricks job, delivered alert, live registry promotion or real operator acceptance.');table(s,[['Demonstrates','Requires a separate pilot'],['Synthetic pipeline and recorded model comparisons','Representative approved operational data'],['Rule signals and anomaly scores','Validated incidents and calibrated review burden'],['Local saved-model reuse','Governed platform deployment and access'],['Prepared review and monitoring exercises','Real human dispositions and durable alert delivery'],['Forecast errors on synthetic observations','Prospective operational performance']],175,[535,595]);
s=slide('Appendix F   Presenter handoff','Alternate presenter: use slides 1–12 for the main narrative. Open the notebook before the session. Prefer the saved executed outputs if compute is unavailable. Demonstrate daily data, one SPC episode, classification comparison, forecasting, artifact reload and drift in that order. Keep the dashboard filtered to the same workload. Use the runbook for exact cells. Never silently substitute old result numbers.');body(s,['Main route: slides 1–12, then selected appendix answers.','Live evidence: counts, signal episode, comparison, forecast, reuse, drift.','Fallback: use this deck and the final saved notebook outputs.','Exact operating steps: docs/presentation-runbook.md']);
await fs.writeFile(path.join(out,'slide-content.json'),JSON.stringify(all,null,2));
await (await PresentationFile.exportPptx(p)).save(path.join(out,'candidate.pptx'));
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(out,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));}
const finalDir=path.join(root,'.build/deck-final'); await fs.mkdir(finalDir,{recursive:true});
const final=path.join(finalDir,`validated-${Date.now()}.pptx`);
const receipt=path.join(out,`validation-${Date.now()}.json`);
await finalizePresentation({workspaceDir:root,candidatePath:path.join(out,'candidate.pptx'),finalPath:final,pythonExecutable:process.env.ARTIFACT_PYTHON || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3'),integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit',...[5,7,8,14,17].flatMap(n=>['--require-native-table-slide',String(n)])],fontPolicy:{basis:'design',families:[font]},requiredNativeChartOwnerSlides:[3],requiredNativeTableOwnerSlides:[5,7,8,14,17],materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:receipt});
await fs.copyFile(final,path.join(root,'docs/SPC_ML_Demo_Walkthrough_Ready.pptx'));
await fs.copyFile(receipt,path.join(out,'validation.json'));
const delivered=await PresentationFile.importPptx(await FileBlob.load(final));
for(let i=0;i<delivered.slides.items.length;i++){const b=await delivered.export({slide:delivered.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(out,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));}
await fs.writeFile(path.join(root,'docs/talking-points.md'),'# Presenter talking points\n\nUse slides 1–12 for the main narrative. The appendix supports technical questions. All counts and metrics describe the final synthetic run. Use `presentation-runbook.md` for exact notebook actions.\n\n'+all.map((v,i)=>`## Slide ${i+1}: ${v.title.replaceAll('\n',' ')}\n\n${v.notes}\n`).join('\n')+'\n## Alternate-presenter handoff\n\nBefore presenting, verify the dataset identifier and run outputs match this deck. Open the notebook and dashboard in advance. If live compute or platform access fails, use saved executed outputs and state the limitation. Do not claim an alert was delivered, a model was promoted or a schedule ran without live evidence. Allow a short pause after the classification comparison to explain that labels come from known SPC rules. Keep future-volume forecasting separate from detecting an unusual pattern.\n');
console.log(JSON.stringify({slides:all.length,font,deck:path.join(root,'docs/SPC_ML_Demo_Walkthrough_Ready.pptx')}));
